# Generated by Django 3.0.7 on 2020-06-13 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_name', models.CharField(max_length=100)),
                ('shop_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
