# Generated by Django 3.0.7 on 2020-06-13 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200613_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='user_owner',
            new_name='owner',
        ),
    ]
